server:
  port: 8082
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/myblog?useSSL=false&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 50
      # 获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000

  redis:
    host: localhost
    port: 6379
    timeout: 10
    jedis:
      pool:
        max-active: 1000
        max-idle: 500
        max-wait: 500

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.swpu.uchain.blog.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true


jwt:
  secret: test
  expiration: 1296000
  tokenStart: "Bearer "
  tokenName: Authorization

pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
  support-methods-arguments: true

aliyun:
  accessKeyId: "LTAI000VKxqr7mn8"
  accessKeySecret: "CTC04KIVZQrwvJNO5E7J2mboGae1pA"
  insertTemplate: "SMS_166655049"
  updatePWTemplate: "SMS_166665985"